require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../mobile_sdk/SalesforceMobileSDK-iOS/mobilesdk_pods'

platform :ios, '13.0'

use_frameworks!

project 'ReactNativeTypeScriptTemplate.xcodeproj'
target 'ReactNativeTypeScriptTemplate' do
  source 'https://cdn.cocoapods.org/'
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  use_mobile_sdk!(:path => '../mobile_sdk/SalesforceMobileSDK-iOS')
  pod 'SalesforceReact', :path => '../node_modules/react-native-force'
end

# To avoid Xcode 12 compilation errors in RNScreens and RNCMaskedView
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNScreens') || pod.name.eql?('RNCMaskedView')
      def pod.build_type
        Pod::BuildType.static_library
      end
    end
  end
end

post_install do |installer|
  # Comment the following if you do not want the SDK to emit signpost events for instrumentation. Signposts are  enabled for non release version of the app.
  signposts_post_install(installer)
  
  # Cocoapods workaround for M1 machines
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
  
  # Keeping Mobile SDK iOS deployment target at 13 (__apply_Xcode_12_5_M1_post_install_workaround changed it to 11)
  installer.pods_project.targets.each do |target|
    if ['SalesforceAnalytics', 'SalesforceSDKCommon', 'SalesforceSDKCore', 'SmartStore', 'MobileSync', 'SalesforceReact'].include?(target.name)
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
