require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../mobile_sdk/SalesforceMobileSDK-iOS/mobilesdk_pods'

platform :ios, '13.0'

use_frameworks!

project 'ReactNativeTypeScriptTemplate.xcodeproj'
target 'ReactNativeTypeScriptTemplate' do
  source 'https://cdn.cocoapods.org/'
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  use_mobile_sdk!(:path => '../mobile_sdk/SalesforceMobileSDK-iOS')
  pod 'SalesforceReact', :path => '../node_modules/react-native-force'
end

# Comment the following if you do not want the SDK to emit signpost events for instrumentation. Signposts are  enabled for non release version of the app.
post_install do |installer|
  signposts_post_install(installer)
end
