platform :ios, '9.0'

project 'iOSNativeSwiftTemplate.xcodeproj'
target 'iOSNativeSwiftTemplate' do

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'SalesforceAnalytics', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceSDKCore', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartStore', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartSync', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'

end
