require_relative './mobile_sdk/SalesforceMobileSDK-iOS/mobilesdk_pods'

platform :ios, '18.0'

project 'Authenticator.xcodeproj'
target 'Authenticator' do
  source 'https://cdn.cocoapods.org/'
  use_frameworks!
  use_mobile_sdk!
  pod 'SwipeCellKit', '2.7.1'
end

post_install do |installer|
  mobile_sdk_post_install(installer)
end
