# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

project 'iOSNativeTemplate.xcodeproj'
target 'iOSNativeTemplate' do

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'SalesforceAnalytics', :path => 'node_modules/SalesforceMobileSDK-iOS'
pod 'SalesforceSDKCore', :path => 'node_modules/SalesforceMobileSDK-iOS'
pod 'SmartStore', :path => 'node_modules/SalesforceMobileSDK-iOS'
pod 'SmartSync', :path => 'node_modules/SalesforceMobileSDK-iOS'

end
