require_relative './mobile_sdk/SalesforceMobileSDK-iOS/mobilesdk_pods'

platform :ios, '18.0'

project 'MobileSyncExplorerSwift.xcodeproj'
target 'MobileSyncExplorerSwift' do
  source 'https://cdn.cocoapods.org/'
  use_frameworks!
  use_mobile_sdk!
end

target 'RecentContactsExtension' do
  use_frameworks!
  pod 'SalesforceSDKCommon', :path => "./mobile_sdk/SalesforceMobileSDK-iOS"
  pod 'SalesforceSDKCore', :path => "./mobile_sdk/SalesforceMobileSDK-iOS"
end

post_install do |installer|
  # Comment the follow if you don't want to support visionOS
  vision_os_post_install(installer)

  mobile_sdk_post_install(installer)
end