platform :ios, '10.0'

project 'ReactNativeTemplate.xcodeproj'
target 'ReactNativeTemplate' do

source 'https://github.com/CocoaPods/Specs.git'

pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',
    'tvOS',
    'jschelpers',
    'cxxreact',
    'ART',
    'RCTActionSheet',
    'RCTAdSupport',
    'RCTAnimation',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
]

pod 'SalesforceAnalytics', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceSDKCore', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartStore', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartSync', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceReact', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'

end
