require_relative './mobile_sdk/SalesforceMobileSDK-iOS/mobilesdk_pods'

platform :ios, '18.0'

project 'EncryptedNotificationTemplate.xcodeproj'
target 'EncryptedNotificationTemplate' do
  source 'https://cdn.cocoapods.org/'
  use_frameworks!
  use_mobile_sdk!

  target 'NotificationServiceExtension' do
    inherit! :search_paths
  end
end

post_install do |installer|
  mobile_sdk_post_install(installer)
end