require_relative './mobile_sdk/SalesforceMobileSDK-iOS/mobilesdk_pods'

platform :ios, '18.0'

project 'iOSNativeLoginTemplate.xcodeproj'
target 'iOSNativeLoginTemplate' do
  source 'https://cdn.cocoapods.org/'
  use_frameworks!
  use_mobile_sdk!
  
  pod "RecaptchaEnterprise", "18.5.0-beta01"
end

post_install do |installer|
  mobile_sdk_post_install(installer)
end
